In [1]:
import json
from datetime import datetime
import kragle as kg
import sys
import pandas as pd
import math
import numpy as np
import scipy.stats as st
import statsmodels.stats.api as sms
from sklearn.metrics import r2_score, mean_squared_error
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab
import matplotlib.ticker as ticker
import sklearn as sk

np.set_printoptions(suppress=True) # prevent numpy exponential.

In [2]:
deepwalk_results = np.loadtxt(fname='success.txt', delimiter=' ', skiprows=1)

In [3]:
deepwalk_profile_ids = deepwalk_results[:,0]
deepwalk_columns = deepwalk_results[:,1:]

In [4]:
print(deepwalk_results[0])
print(deepwalk_profile_ids[0])
print(deepwalk_columns[0])

[ 7.92834656e+17 -2.33736800e-02 -7.41214000e-02  4.89024860e-02
 -7.09074800e-02  1.37341805e-02 -2.50322700e-01 -2.44972150e-01
 -1.36896540e-01  3.79769130e-02 -3.66139100e-01 -1.06888190e-01
 -1.03669570e-01 -2.31861650e-01  1.37896630e-01  4.85645560e-01
  5.48315200e-02  2.89309400e-02 -2.75901910e-02  9.21273500e-02
 -1.87523260e-01 -7.96542500e-03  5.61375130e-02 -2.22922000e-01
 -9.33391450e-02 -2.49016820e-01  3.80636640e-02  1.53096110e-01
  4.54617900e-01 -6.85669440e-05  2.53950260e-02  8.22962750e-02
  1.49207550e-01  1.29822550e-01 -7.28711440e-03 -1.11241350e-01
  6.26259440e-03 -1.90107430e-01  2.04679840e-02  3.12234370e-01
 -1.32626610e-01  6.11354080e-02  2.40695060e-01 -1.35825400e-01
 -7.69791700e-02 -7.60703100e-03 -1.25790010e-02  3.02192620e-03
 -1.36677790e-01 -3.66839050e-01  3.86278850e-02  6.62494900e-03
 -8.27743600e-04  1.94376510e-01  1.03079850e-01  1.30742550e-01
  2.11160140e-01  8.81826650e-02  3.50890500e-01  2.65030350e-01
  3.08337330e-01  2.24712

In [5]:
# https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html
from sklearn.manifold import TSNE

dimensions_reduced = sk.manifold.TSNE(n_components=2,
                 perplexity=30.0, 
                 early_exaggeration=12.0, 
                 learning_rate=200.0,
                 n_iter=1000,
                 n_iter_without_progress=300,
                 min_grad_norm=1e-07,
                 metric='euclidean', 
                 init='random', 
                 verbose=0,
                 random_state=None, 
                 method='barnes_hut', 
                 angle=0.5, 
                 n_jobs=None).fit_transform(deepwalk_columns)

In [6]:
write_to_file = np.concatenate((deepwalk_profile_ids.reshape(-1,1), 
                                    dimensions_reduced), 
                               axis=1)
print(write_to_file[0:5])

[[ 7.92834656e+17  3.43298984e+00  3.85535278e+01]
 [ 8.64892250e+17 -1.94336319e+01 -2.48539448e+01]
 [ 9.36947466e+17 -3.34842563e+00  4.55704737e+00]
 [ 8.64885425e+17  7.21987152e+00 -3.62936516e+01]
 [ 8.64886434e+17 -3.78393059e+01  9.07412148e+00]]


In [7]:
np.savetxt('tSNE.txt', write_to_file, fmt='%d %d %d')